### ISSUE TITLE
relative path mismatch on Windows when running at fast-jar mode

### ISSUE THREAD

**Issue by andyhan** [quarkiverse/quarkus-quinoa#100]
quinoa extension version: 1.0.5
On Windows 11, first using `pnpm create vite` to create a empty front project, no matter vue or react, then modify the quarkus app's properties file according to quinoa docs, and then exec ` java -jar .\target\quarkus-app\quarkus-run.jar` after `mvn clean package -D skipTests` to start the app, then visit http://localhost:8080, you will found that all the web resource startwith `/assets/` are not found in browser.

the content of `target\quinoa-build` is show as following:

```
|   favicon.ico
|   index.html
\---assets
        index.ac618489.js
        index.f0ced7b7.css
        logo.03d6d6da.png
```

when exec `mvn package`, the console will print 
```
[INFO] [io.quarkiverse.quinoa.deployment.QuinoaProcessor] Quinoa generated resource: '/assets\index.ac618489.js'
[INFO] [io.quarkiverse.quinoa.deployment.QuinoaProcessor] Quinoa generated resource: '/assets\index.f0ced7b7.css'
[INFO] [io.quarkiverse.quinoa.deployment.QuinoaProcessor] Quinoa generated resource: '/assets\logo.03d6d6da.png'
[INFO] [io.quarkiverse.quinoa.deployment.QuinoaProcessor] Quinoa generated resource: '/favicon.ico'
[INFO] [io.quarkiverse.quinoa.deployment.QuinoaProcessor] Quinoa generated resource: '/index.html'
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 11534ms
```

I do some investigation, and found that this issue is caused by the Path Separator difference between Windows ('\') and Unix ('/'), the browser always recognize the Unix style path separator not windows, but the Java NIO path's relativize() method will return the OS related relative path, which means on Windows it will always return a path contains '\' as the path separator not '/'. this will cause during runtime, the route context path will never match the record in static generated build resource items.

I suggest to modify this line https://github.com/quarkiverse/quarkus-quinoa/blob/993166deee1141d35e13423dd9f9172ad9ecccb7/deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java#L216 

```
final String name = "/" + targetDir.relativize(file).toString().replace('\\', '/');
```

It works on both Windows and Linux / MacOS.
@ia3andy

**Comment by ia3andy** [comment]
Good catch @andyhan! Would you provide a PR today? I will perform a release later..

**Comment by andyhan** [comment]
> @andyhan I could easily do it, but better have you part of the contributors for your contribution :-)

I just submit the PR #101.
