### ISSUE TITLE
SPA-Routing not working with Quarkus 2.11.0.CR1

### ISSUE THREAD

**Issue by alexander-dammeier** [quarkiverse/quarkus-quinoa#144]
I updated my Quarkus-App to 2.11.0.CR1. The frontend is correctly served at the intended path but also at the paths of my Rest-API.
With Quarkus 2.10.2.Final everything works fine.

My quinoa config in application-properties:
```
quarkus.quinoa.ui-dir=voting-tool-frontend/
quarkus.quinoa.build-dir=dist/
quarkus.quinoa.enable-spa-routing=true
quarkus.quinoa.package-manager=npm.cmd
```
I use Vue 3 for my frontend.

My Rest-API should be reachable under `/api` as defined at my Application class. 
```
@ApplicationPath("api")
@Blocking
class JaxRsApplication : Application() {
}
```

**Comment by ia3andy** [comment]
Thanks for the heads up, I will have a look today!

**Comment by ia3andy** [comment]
Until I publish a fix, you can use https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/#quarkus-quinoa_quarkus.quinoa.ignored-path-prefixes

**Comment by ia3andy** [comment]
@alexander-dammeier could you check that you are using quinoa 1.1.1?

**Comment by ia3andy** [comment]
@alexander-dammeier 

Now that I see you are using RESTEasy Reactive, as a best practice, I suggest you to do this (and adjust the relative path in the resources which can be `/` or ``): 
```properties
quarkus.resteasy-reactive.path=/api
```

Then, you can remove the `quarkus.quinoa.ignored-path-prefixes=/api` as Quinoa is now ignoring this path by default :)

Still, I will have a look to this bug!

**Comment by ia3andy** [comment]
Ok I reproduced the bug..

**Comment by alexander-dammeier** [comment]
I deleted my JaxRsApplication class and added `quarkus.resteasy-reactive.path=/api` as you mentioned. This also did the trick! So maybe it really is something with the annotation.

**Comment by ia3andy** [comment]
The fix is ready, I will publish a new release later today.

FYI, the bug is not due to the annotation, but to a change in the routing order starting from 2.11. 

The reason why the path gets ignored with the config instead of the annotation is due to the fact that Quinoa detects the path configuration but not the annotation (I am not sure if reading the `@ApplicationPath("api")` annotation would be possible from another extension cc @geoand)

**Comment by geoand** [comment]
Extensions can read annotation they wish to, there is no limitation.

But IIRC there is also a build item in RR that gives you the result of scanning for such annotations
