### ISSUE TITLE
Add support for yarn install

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#174]
Now that we have support for NodeJS and NPM install, adding yarn should be a piece of cake:

```properties
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=16.17.0
quarkus.quinoa.package-manager-install.yarn-version=1.22.19
```

Default download root: https://github.com/yarnpkg/yarn/releases/download/

**Comment by ia3andy** [comment]
If implementing this, you might also want to implement #175

**Comment by melloware** [comment]
I will add this
