### ISSUE TITLE
Add support for pnpm install

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#175]
Now that we have support for NodeJS and NPM install, adding pnpm should be a piece of cake:

```properties
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=16.17.0
quarkus.quinoa.package-manager-install.pnpm-version=7.12.0
```

Default download root: https://registry.npmjs.org/pnpm/-/

**Comment by ia3andy** [comment]
If implementing this, you might also want to implement #174

**Comment by melloware** [comment]
I will add this
