### ISSUE TITLE
Improve Playwright support 

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#198]
Currently the [QuarkusPlaywrightManager](https://github.com/quarkiverse/quarkus-quinoa/blob/main/testing/src/main/java/io/quarkiverse/quinoa/testing/QuarkusPlaywrightManager.java) is not giving a lot of flexibility for consumers (hard coded browser and options).

Also it would be nice to have a doc (or links) to setup CI with Playwright and Quinoa.

**Comment by melloware** [comment]
@ia3andy i am wondering if Playwright should be its own Quarkus Extension so that way advanced customization and configuration can be applied?

**Comment by ia3andy** [comment]
done https://github.com/quarkiverse/quarkus-playwright
