### ISSUE TITLE
Quinoa re-routes to "/", but should route to `quarkus.http.root-path`

### ISSUE THREAD

**Issue by stephan-strate** [quarkiverse/quarkus-quinoa#224]
### Actual behavior

The `QuinoaSPARoutingHandler` re-routes requests to "/". The application shows error "Resource not found".

See: https://github.com/quarkiverse/quarkus-quinoa/blob/main/runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java#L36

### Expected behavior

If the application uses `quarkus.http.root-path=/some-base-path`, Quinoa should re-route requests to "/some-base-path".

Using `quarkus.http.root-path` helps hosting multiple applications under the same domain.

**Comment by ia3andy** [comment]
Thanks for reporting, we will have a look very soon!
