### ISSUE TITLE
CORS Issue with Create React App

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-quinoa#231]
**Quinoa:** 1.2.3
**Quarkus:** 2.15.2.Final

I following your instructions and I have my Create React App working when I run `mvn quarkus:dev`.

The app is served at `http://localhost:8080` and the React app can hits its REST services at 8080.   

However when I switch to the live coding port 3000 `http://localhost:3000` the React app renders but I get CORS errors hitting localhost:8080.

My HTTP is configured correctly and my CORS setting is `true`.

```
# HTTP
quarkus.http.port=8080
quarkus.http.enable-compression=true
quarkus.http.cors=true
quarkus.http.filter.others.header.Cache-Control=no-cache
quarkus.http.filter.others.matches=/.*
quarkus.http.filter.others.methods=GET
quarkus.http.filter.others.order=0
quarkus.http.filter.static.header."Cache-Control"=public, immutable, max-age=31536000
quarkus.http.filter.static.matches=/static/.+
quarkus.http.filter.static.methods=GET,HEAD
quarkus.http.filter.static.order=1
# Quinoa
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=16.17.0
quarkus.quinoa.dev-server.port=3000
quarkus.quinoa.enable-spa-routing=true
```

However whenever using the Live Coding port 3000 it cannot access the services at localhost:8080 with CORS error. _"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/entity/cars/manufacturers. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200."_

![image](https://user-images.githubusercontent.com/4399574/211210412-98611d8d-3cd7-4177-964b-43c92b4fa9d3.png)

![image](https://user-images.githubusercontent.com/4399574/211207920-d27fb055-3eef-469c-92cd-f77bc9653f15.png)

I did not see anything in your guides about anything special that needs to be done for CORS to work properly?

**Comment by melloware** [comment]
It looks like these are the only headers you are forwarding?

```java
 private final List<String> HEADERS_TO_FORWARD = List.of(
            HttpHeaders.ACCEPT_RANGES.toString(),
            HttpHeaders.CONTENT_RANGE.toString(),
            HttpHeaders.CONTENT_LENGTH.toString(),
            HttpHeaders.CONTENT_TYPE.toString());
```

shouldn't `Access-Control-Allow-Origin` be in this list as well?

**Comment by ia3andy** [comment]
I am not sure what you are trying to achieve, the CORS are supposed to be done by the backend api in case you are actually doing cross-origins requests (from one host to another). But in your case, the CORS are happening because you are requesting http://localhost:3000/ instead of http://localhost:8080/

Why not use http://localhost:8080/?

**Comment by melloware** [comment]
So the behavior I am seeing is if I make a change to the React code I don't see it change in 8080 but I do in 3000. 

It's like 8080 is serving a static copy?  I will try again today.

**Comment by ia3andy** [comment]
> So the behavior I am seeing is if I make a change to the React code I don't see it change in 8080 but I do in 3000.
> 
> It's like 8080 is serving a static copy? I will try again today.

Ok so the problem might be different, as 8080 should serve the same as 3000 but with the backend on the same port

**Comment by melloware** [comment]
OK yeah I tried again today and the hot reloading on 8080 seems to be working.  Must have just been something strange yesterday.  Thanks for the response!

**Comment by melloware** [comment]
btw @ia3andy great project.  I had done all this by hand using the Frontend plugin until I found this project :0

I modified my project to use your extensions now and it cleaned up my build so much!

Project: https://github.com/melloware/quarkus-monorepo
