### ISSUE TITLE
Guide to production usage of Quinoa

### ISSUE THREAD

**Issue by YassinHajaj** [quarkiverse/quarkus-quinoa#243]
In the official documentation, a schema shows how the interactions between the browser, vert.x, quinoa works in a production environment.

However, I cant find a document anywhere explaining how to set this up.

When packaging my app, the quinoa folder gets created inside of target but nothing gets included within my jar file.

Is this something that will come still ? Or is it already available but not documented ?

PS: i know I could use the frontend plugin or other techniques for this but Id rather just use Quinoa

**Comment by ia3andy** [comment]
Do you have a sample project to reproduce?

**Comment by YassinHajaj** [comment]
Hi @ia3andy ,

Thanks a bunch for the quick answer. On my side I'd put that on standby for a few days as you can see.
I apologize because the problem was related to my personal setup instead of the project itself.
After a fix on my server, I was able to access the frontend indeed.

Thanks again.

Yassin
