### ISSUE TITLE
Consider delegating to `npm run test` during maven test phases

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-quinoa#247]
I got caught out recently because I'd been relying on my CI to tell me if I broke tests. I was accustomed to everything happening via maven in my Quinoa project, so I didn't have any steps in my CI to run `npm run test`. 

Should the maven test-running steps invoke npm testing steps? This would be be handy in some ways, but there are also arguments against it, similar to the arguments in #59. Among other things, it would slow builds down. If people didn't expect Quinoa to run their tests, they might end up running tests twice. (Locally, this would almost certainly happen to me, because I have one terminal open in Webstorm with my npm tests, and another window where I'm running `quarkus dev` in a Java IDE.)  

Opening this issue to track the discussion and the decision. :)

**Comment by ia3andy** [comment]
Maybe I should update the doc to make it more obvious though

**Comment by holly-cummins** [comment]
I raised https://github.com/quarkiverse/quarkus-quinoa/pull/249, since I had the documentation and your example in front of me.
