### ISSUE TITLE
Content Type Negotiation impossible

### ISSUE THREAD

**Issue by YassinHajaj** [quarkiverse/quarkus-quinoa#251]
Hello,

I have the frontend and the backend running in the same Quarkus instance (of course) and the backend exposes an API for which content negotiation is necessary.

I noticed the following piece of code

```
final MultiMap headers = request.headers();
// Workaround for issue https://github.com/quarkiverse/quarkus-quinoa/issues/91
// See https://www.npmjs.com/package/connect-history-api-fallback#htmlacceptheaders
// When no Accept header is provided, the historyApiFallback is disabled
headers.remove("Accept");
```

This makes it impossible unfortunately for API clients to use content type negotiation using the Accept header in dev mode.
Can this be fixed somehow ?

I guess if we can find a way to compare the dev server port config with the actual request port, it should be feasible.

I tried to find my way in the code and write a PR but so far I didn't find a solution to retrieve the actual request port from the context.

**Comment by YassinHajaj** [comment]
Hello again,

For now I'll exclude the api by prefixing it with /api and using quarkus.quinoa.ignored-path-prefixes.
But ideally of course, this shouldn't be necessary right ?

**Comment by ia3andy** [comment]
what extension are you using for the api? 
When using resteasy-reactive,  just set `quarkus.resteasy-reactive.path=/api` then all your api gets prefixed and Quinoa will ignore that path by default (no need to set `quarkus.quinoa.ignored-path-prefixes.`).

This "workaround" is only affecting devmode and is currently the only way to deal with library using `connect-history-api-fallback` behind the scene (react-script, angular, ...). We would make this configurable if someone else is having problem with this.

I think it's a good practice to prefix the api when creating a full stack application.

Closing for now.
