### ISSUE TITLE
This is a bug in Quinoa -- it stops at the space in username

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkiverse/quarkus-quinoa#252]
I was running an apllication which uses Quinoa but i am not able to run while i follow all rules during this run

![Screenshot (42)](https://user-images.githubusercontent.com/91419219/220065252-cb118ffd-622e-4e31-b86c-f466ed2f308c.png)

# Second img

![Screenshot (43)](https://user-images.githubusercontent.com/91419219/220065403-6ea307c1-8133-4ad3-bb55-f0b745aedb2e.png)

**Comment by ia3andy** [comment]
Thanks for reporting @shivam-sharma7

**Comment by shivam-sharma7** [comment]
hey @ia3andy @johnaohara I think now it will be not giving me error like above.

**Comment by ia3andy** [comment]
@johnaohara you are good to update the version :)

**Comment by johnaohara** [comment]
@ia3andy many thanks!
