### ISSUE TITLE
Shutting down quarkus dev on Windows does not terminate quinoa dev server

### ISSUE THREAD

**Issue by alexkolson** [quarkiverse/quarkus-quinoa#280]
If you "Ctrl+C" the `quarkus dev` command, the main quarkus process dies but the quinoa dev server doesn't. As a quarkus user, I would expect everything that is being spawned by quarkus to also be killed by quarkus. Is this something in quinoa's control?

This behavior also manifests itself when starting/stopping the quarkus process in IntelliU.

If this is intended behavior, which I can live with, then it would be great to document this behavior in the extension docs, and possibly provide a way for us as users to tell the quinoa dev server to be killed when quarkus is killed.

**Comment by ia3andy** [comment]
Hey @alexkolson, Thanks for reporting this issue.

This is not a normal behavior, Quinoa is destroying the dev process and it's descendant:
https://github.com/quarkiverse/quarkus-quinoa/blob/main/deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java#L69

Maybe the dev process doesn't want to be killed for some reason?
We could try to make the `stopDev` more verbose when it fails, also, maybe there are some way to improve it..

Would you try to debug why your process is not stopping in the current impl?

**Comment by alexkolson** [comment]
Hi @ia3andy thanks for the quick response!

I can't reliably reproduce this, as sometimes the Quinoa process is killed successfully. Furthermore, it doesn't seem fair to leave you with an open issue where I have not provided more detailed information. If I keep having this issue intermittently, I will spend some time debugging and create a new issue with more details. It is totally possible, and frankly probably more likely, that something else on on my Windows machine totally out of Quinoa/Quarkus's control is happening.

If debugging leads me back to something Quinoa-specific, I'll be back :)

**Comment by ia3andy** [comment]
@alexkolson 1.2.7 (Quarkus 2.x) and 2.0.0 (if using quarkus 3.X) should contain the patch 👍

**Comment by alexkolson** [comment]
Thank you!!! You sir, are awesome!!

Andy Damevin ***@***.***> schrieb am Mi. 22. März 2023 um
15:00:
