### ISSUE TITLE
Allow to serve Quinoa application on a specific path

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-quinoa#302]
The Quinoa extension operates in a particular way, as illustrated in the attached image. When an HTTP request is made, it first reaches the Quinoa extension. If the extension doesn't find the resource, it looks for it in META-INF/resources, and if that fails too, it forwards the request to the REST API. However, the problem is that if we intend to develop a web application that uses Quarkus Qute to handle the requests in the root path '/', we can't do that since Quinoa has higher priority, and it would serve the Quinoa app instead.

To resolve this issue we can modify the Quinoa extension's configuration to serve the application in a different path. For instance, we can configure the extension to serve the Quinoa app in the path '/quinoa', while the Quarkus Qute-based web application would be served in the root directory '/'.

By implementing this solution, we can have both the Quinoa app and the Quarkus Qute-based web application running simultaneously, without any conflicts.

The following Qute-based web application is never served since the Quinoa-based application gets served.

```java
@Path("/")
@ApplicationScoped
public class HtmlResource {

    @Inject
    Template index;

    @Inject
    Template cart;

    @GET
    public TemplateInstance getIndex() {
        return index.instance();
    }

    @GET
    @Path("cart")
    public TemplateInstance getContant() {
        return cart.instance();
    }

}
```

![](https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/_images/quinoa-runtime-prod.png)

**Comment by liquidnya** [comment]
You can now set the `quarkus.quinoa.ui-root-path` property to set the path of Quinoa.
