### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkiverse/quarkus-quinoa#312]
The idea is to add a PR template.

**Comment by shivam-sharma7** [comment]
> I don't understand?

Pull request templates allow your organizations or repo to have a default text when you create a pull request on GitHub like- Describe your changes, fixed #issue, and  some checkbox

**Comment by melloware** [comment]
Oh OK I see what you mean.

**Comment by shivam-sharma7** [comment]
> Oh OK I see what you mean.
 May you assign me?
