### ISSUE TITLE
Package is not working under windows

### ISSUE THREAD

**Issue by fblan** [quarkiverse/quarkus-quinoa#341]
### Describe the bug

Packaging phase is not working on windows.
It seems that it is due to PackageManager processBuild function, that try to move buildDir content to targetBuildDir.
It seems that Files.move function on a not empty folder will work only on unix system (https://docs.oracle.com/javase/tutorial/essential/io/move.html) 

ps: Thanx for this very usefull extention!

### Quinoa version

2.0.3

### Quarkus version

3.0.1.Final

### Build / Runtime

Vite

### Package Manager

NPM

### Steps to reproduce the behavior

create a quinoa project on windows.
run "mvn package"
the build fail with AccessDeniedException

### Expected behavior

build is successfull.

**Comment by melloware** [comment]
let me give this a try.

**Comment by melloware** [comment]
Working fine for me.

OS: Microsoft Windows [Version 10.0.22621.1555]

Run `mvn clean package` on this example project: [vite.zip](https://github.com/quarkiverse/quarkus-quinoa/files/11346319/vite.zip)

**Comment by ia3andy** [comment]
Maybe files access?

**Comment by fblan** [comment]
The example provided by @melloware is working perfectly on my machine!
So I will investigate to understand what is wrong with my project (I will have look for files access @ia3andy ) 
Thanks to both of you :)

**Comment by fblan** [comment]
It seems even my project is working today.
So it was definitely a problem on my side! Sorry guys, and thank you so much for your help!
Next time I will restart my computer and retry before to go to github :)

**Comment by melloware** [comment]
I will close for now thanks for reporting back!  If you do discover the root cause let us know and we can re-open this ticket!
