### ISSUE TITLE
Add docs for quarkus-quinoa

### ISSUE THREAD

**Issue by shivam-sharma7** [quarkiverse/quarkus-quinoa#352]
## Feature idea
Add docs about quarkus-quinoa that how to set up project locally and run.

**Comment by shivam-sharma7** [comment]
@melloware I have seen Quarkus project have lot of problem in native windows

**Comment by melloware** [comment]
Yep most of the Quarkus Devs like @ia3andy use MacOS or native Linux as their OS and it always just works.  You and I use Windows everyday and I have seen a lot of quirks even building Quarkus itself I have issues in Windows.  So a lot of times I use WSL (Windows Subsystem for Linux) in Ubuntu  instead.

**Comment by shivam-sharma7** [comment]
We need to start a forum on Quarkus for this
