### ISSUE TITLE
Open Webcomponents assets are served in dev mode, but not in prod mode 

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-quinoa#364]
### Describe the bug

I'm working on a Lit-Quinoa project. [Open Webcomponents](https://open-wc.org/) starter projects put assets in a top level assets folder. In a Quinoa project, that would be `./src/main/webui/assets/`. These resources are visible when running in dev mode, but not when running packaged jars.

To make things work in prod, the images need to be in `./src/main/resources/META-INF/resources/assets/`.

### Quinoa version

2.0.4 and also 1.2.6 

### Quarkus version

3.0.4.Final

### Build / Runtime

Other

### Package Manager

NPM

#### Reproducer with lots of code (sorry)

```
git clone https://github.com/holly-cummins/redis-cache-cache.git
cd redis-cache-cache 
git checkout 20fe33bf0a7c3127178e164376f8c6b24fc06086
cd places-service
quarkus dev 
```
Now, in a new window
                                  
```
cd frontend
rm ./src/main/resources/META-INF/resources/assets/map.png
mvn clean package 
java -jar target/quarkus-app/quarkus-run.jar
```

Visit localhost:8080 and click the "add all places" button. You should see this:
<img width="1612" alt="image" src="https://github.com/quarkiverse/quarkus-quinoa/assets/11509290/055df870-02c5-4f40-bb4b-3fde4c8581c1">

There's no map. (If you don't see the names either, you forgot to click 'add all places'.)
Now run 

```
quarkus dev
```

After clicking 'add all places,' you should see this: 

<img width="1612" alt="image" src="https://github.com/quarkiverse/quarkus-quinoa/assets/11509290/aa2f74bf-8bae-4766-82aa-b5daee079e94">

Ignoring the fact that Copenhagen has been drawn in the ocean, this is clearly better. 

#### Home-rolled reproducer

Alternatively, it should work to create a Lit Open Webcomponents app, following the [generator instructions](https://open-wc.org/guides/developing-components/getting-started/), basically 

```
npm init @open-wc
```

Then, if you copy that app into a Quinoa quickstart, I think the cool rotating OpenWC logo from the assets folder will be visible with `quarkus dev`, and not with a prod build. 

#### Note 

It took me a while to reproduce this (@cescoffier kept telling me there was a problem, and it kept working on my machine). It turns out the problem was I'd run with `quarkus dev` first, and Firefox was caching the image file. 

These steps helped undo the cache (or just checking in prod in a different browser also works, and is easier):
     - Open the developer toolbox (Ctrl+Shift+I or Cmd+Opt+I on Mac).
    - Click the settings button (near the top right).
    - Scroll down to the Advanced settings on the bottom right.
    - Tick the option "Disable Cache (when toolbox is open)".
    - Refresh the page.

**Comment by melloware** [comment]
OK so from looking at your project without trying it Quinoa is running your build step.

```json
"build": "rimraf dist && rollup -c rollup.config.js --dir build && npm run analyze -- --exclude dist",
```

That looks like it builds to /src/main/webui/build.

Quinoa copies that /build directory by default with this setting..

```properties
quarkus.quinoa.build-dir=build
```

However your `assets` folder is outside of that build folder that gets copied.  Do I have that correct?

**Comment by holly-cummins** [comment]
I think it's close, @melloware! My `assets` folder is outside of the `build` folder, and the rollup step should copy it into the `build` folder, from which Quinoa should serve it. The app is just based on an openwc generator, and `assets` is in the standard place the openwc generator puts it, so it should Just Work. 

What's puzzling me is figuring out what the misconfiguration is. I can't reproduce using a fresh openwc generator and fresh quinoa codestart (the 'home-rolled' reproducer I suggested above.) What's confusing me is the rollup and package.json scripts are almost identical between my app and the fresh re-create, but one works and one doesn't. 

I think it must be a `build`/`dist` confusion, but it's not obvious to me yet.

**Comment by melloware** [comment]
Yes that is the issue the `assets` are not being copied into the `build` folder.  You don't have to use `build` if their main folder is supposed to be `dist` just use `dist` and set...

```
quarkus.quinoa.build-dir=dist
```

That is what I do for NextJS docs since their build folder is `out` by default.  Let me know what you find out.

**Comment by melloware** [comment]
Once you resolve it we can always update the Quinoa docs and add a WebComponents section like we added Create React App and NextJS.

**Comment by holly-cummins** [comment]
Thanks, @melloware! I think I see the issue. If [`import.meta.url`](https://modern-web.dev/docs/building/rollup-plugin-import-meta-assets/) is used in the `<img`, for example, 

```
const logo = new URL('../assets/open-wc-logo.svg', import.meta.url).href;
```

then rollup (as configured in the starter) will copy the assets across into the built artefact. Otherwise, it won't, and I need the [`rollup-copy` plugin and some extra config](https://lit.dev/docs/tools/production/#modern-only-build).

It still feels like a bit of a bug that the images are there with `npm start` and not with `npm build,` but that's an issue with the open-wc starter. So I'll close this.

**Comment by melloware** [comment]
Awesome thanks for the update!
