### ISSUE TITLE
Self-configuring build dir?

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-quinoa#365]
## Feature idea

This follows on from a discussion on [another issue](https://github.com/quarkiverse/quarkus-quinoa/issues/364#issuecomment-1572635588). When using open-wc starters, I either need to set my quinoa build dir to `dist`, or adjust the rollup config to output to a different directory. 

There are a few common patterns for build dirs - `build`, `dist`, `out` ... would there be negative consequences if we just ... checked them all? The one we might not be able to work out is angular, which uses `dist/app-name`. In some other cases users would definitely still need to configure the build dir, but they might be fewer. 

If we were self-configuring on the build dir, the next question is whether we'd also want to check common ports. Checking ports seems a bit riskier than checking dirs, since I think it's unlikely a single application would have both `/dist` and `/out` dirs, but it's plausible a single system could have some app listening on `4200` and another app elsewhere listening on `3000`. That is, the directory is local, but the port is global for the whole system. 

It may be that if we don't self-configure the port, there's no point trying to guess the build dir, since users will need to do configuration anyway for most frameworks.

**Comment by melloware** [comment]
I like this idea. Maybe even the build directory defaulting to `build` could be a List and have more than 1 directory like `build,out,dist` and it would check and copy any or all of them?

**Comment by ia3andy** [comment]
I also like the idea:
- by default we use a list of dirs to check
- we take the first one found in the list
- if more than one is found, we display a warning
- it's still configurable with the current config key

@shivam-sharma7 this one is a good first coding issue for you

**Comment by holly-cummins** [comment]
Displaying a warning is a good improvement, @ia3andy,  that lessens the "we try to be too clever and do the wrong thing" risk. 

I was thinking more about the Angular scenario, and we could make a good guess at the directory, but we'd have to read the `package.json` to get the `name` field. If we're doing that, we could also peek at the start scripts and application dependencies to make a guess at the port. "If the start script runs `ng something something`, I should listen on 4200." But that's much fancier, so should probably be a follow-on feature – if we want to do it at all.

**Comment by ia3andy** [comment]
> field

That's also a very good idea @holly-cummins, for some reason, it never came to my mind :).  Quinoa is all about being clever and try to be zero-config for all the base use cases. I am all for it as soon as it stays configurable. 

The great thing about this idea is that it would allow to have proxied dev mode by default.

I am all for adding framework specific defaults and framework detection (this is another issue though).

**Comment by ia3andy** [comment]
@melloware  wdyt?

**Comment by holly-cummins** [comment]
I raised #367 for the second-phase of super-support for other frameworks :)

**Comment by melloware** [comment]
I really like this idea...Basically if a configuration is provided for a value then use it, else try and auto-detect the value from the package.json.

**Comment by ia3andy** [comment]
I think this all fit into framework detection right?
build-dir, port, and also maybe commands (start, dev, test, build ...)

**Comment by holly-cummins** [comment]
I guess it depends how we want to do it; I raised two tickets because there was a quick win (just use a list for build dirs), and then there's the more complex "read the package.json". But certainly if we do the other ticket quickly, there's no point doing this one, and it sounds like you're on the case with that!
