### ISSUE TITLE
Read package.json to work out what framework is being used, to self-configure port and build-dir even for Angular apps

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-quinoa#367]
## Feature idea

 #365 reduces the amount of configuration users need to do for various framework's build dirs. It can't handle angular apps, though, because the build dir is of the form `/dist/<app-name>`. 
 
If we read the package.json to get the name field, we can make a very good guess at the build dir for angular apps. If we're doing that, we could also peek at the start scripts and application dependencies to make a guess at the port. "If the start script runs ng something something, I should listen on 4200," and so on for Vite, Next.js, etc. 
 
## Additional information

See also discussion in #365.

**Comment by jonkoops** [comment]
I think a good approach for this would to not make it too 'magical', but instead have separate extensions/plugins for specific frameworks/bundlers, with their own configs. For example, a `quarkus-quinoa-angular` or `quarkus-quinoa-vite`.

**Comment by melloware** [comment]
@jonkoops I definitely know what you mean but from a Quarkus perspective its all about minimizing configuration to make a great developer experience.  So I like @holly-cummins ideas all the while leaving the flexibility open to configure it.

However I think we could also have a `/samples` directory here with a small sample app using Vite, Angular, React, NextJS etc so people could easily just start with one of those.

**Comment by holly-cummins** [comment]
A samples dir would be useful to users, but the downside of a samples dir is that we'd then find ourselves in the business of maintaining starters for a whole bunch of frameworks, unless we left out the javascript part of the framework. And you know how javascript is .... it doesn't stay still for long. :)

We could avoid the issue by calling out to create-react-app, `npm init @open-wc`, etc from our CI. Then we could run tests against each framework's sample and make sure we work. That'd be a nice enhancement. 

(If we had just the quarkus part in the sample, with no framework content, I think the interesting bit would be the `application.properties,` which could just live in the docs instead.)

**Comment by melloware** [comment]
Let me work on a Draft PR of framework detection for everyone to review...

**Comment by melloware** [comment]
OK I got it all working. Code review comments welcome!

**Comment by holly-cummins** [comment]
Yaaaaaay! 🥇

**Comment by melloware** [comment]
@holly-cummins I didn't test your Web Components variant of the "framework" but let me know if it works for you.  You should see logging about it "auto-detecting" your framework and setting the port etc.
