### ISSUE TITLE
Predicate based HotDeployment 

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-quinoa#405]
we might be able to replace the scanning by the new predicate (it would make things way simpler): https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/java/io/quarkiverse/web/bundler/deployment/WebAssetsScannerProcessor.java#L59-L60

**Comment by ia3andy** [comment]
Ok, since Quinoa directory is outside default watched files (could also be outside the project dir), we can't use the Predicate<String>.
