### ISSUE TITLE
Improve doc, split pages add nav

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#413]
## Feature idea

The doc has grown and needs to be refactored and improved.

For the nav, see https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html has example:
https://github.com/quarkiverse/quarkus-helm/tree/main/docs/modules/ROOT

We could have:

_In bold what should be on the **nav**.
In Italic what should be a page_

- **_Getting Started_**
  - **How it works**
  - **Setup project** (instead of "installation")
    - **New project** 
      - CLI, 
      - code.quarkus.io
    - **Existing project** 
      - Add Quinoa (dependency or via CLI)
      - Add `src/main/webui` (or configure)
      - Configure NodeJS installation (optional)
  - **Framework Configuration**
    - Auto-detected (bullet list of frameworks with link to creator (and link to setup if needed))
    - Other frameworks (Configure port or manual dev and start build command with links to Advanced Configuration )
  - **Live coding** (quarkus dev)
  - **Production build**
- **_Testing_** (moved up)
- **_Advanced configuration_** (instead of "How to use the extension" and add a). 
  - all existing sections in the nav 
  - Frameworks with Setup (Angular, Svelte, ...)
- **_Configuration Reference_**

The goal is to make it easier to digest. This is up to suggestion.

**Comment by ia3andy** [comment]
@shivam-sharma7 @melloware any thoughts?

**Comment by shivam-sharma7** [comment]
@ia3andy This is a good idea, But little bit confused that we need to fork the repo and clone... or we need to setup a new project for this and you mean everything going from scratch?
