### ISSUE TITLE
Use quarkus-playwright

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#499]
https://docs.quarkiverse.io/quarkus-playwright/dev/

- We should keep quinoa-testing as it contains profiles, we can add quarkus-playwright as a dependency of quinoa-testing.
- The doc needs to be updated

**Comment by ia3andy** [comment]
@shivam-sharma7 this is a real coding and doc issue, go for it! 

As this is important as a maintainer to be autonomous, please only ask questions if you are sure you can't answer it by yourself or from the internet.

Good luck :)

**Comment by shivam-sharma7** [comment]
@ia3andy Here already some test present- https://github.com/quarkiverse/quarkus-quinoa/blob/main/integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaRootPathTest.java

would you like to clarify a bit more what are steps?

**Comment by shivam-sharma7** [comment]
Is this extention published extensions on registry.quarkus.io

see error

```
PS C:\Users\shivam sharma\Desktop\My Project\open-source\quarkus-quinoa\testing> mvn quarkus:add-extension -Dextensions="io.quarkiverse.playwright:quarkus-playwright"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< io.quarkiverse.quinoa:quarkus-quinoa-testing >------------
[INFO] Building Quarkus - Quinoa - Testing 999-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:3.3.0:add-extension (default-cli) @ quarkus-quinoa-testing ---
[INFO] [ERROR]  Nothing installed because keyword(s) 'io.quarkiverse.playwright:quarkus-playwright' were not matched in the catalog.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.405 s
[INFO] Finished at: 2023-09-09T19:09:32+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.3.0:add-extension (default-cli) on project quarkus-quinoa-testing: Unable to update the pom.xml file: Unable to add extensions -> [Help 1]

**Comment by shivam-sharma7** [comment]
@melloware have any idea?

**Comment by melloware** [comment]
You might have to add it to the Pom.xml manually.

**Comment by shivam-sharma7** [comment]
@melloware Should we keep in pom.xml?
```
 <playright.version>1.37.0</playright.version>
```
because we are going to use `quarkus-playwright ` my question is all imports from `com.microsoft.playwright.BrowserContext` would change in `io.quarkiverse.playwright.BrowserContext`?

**Comment by melloware** [comment]
Yes I think you can remove that Playwright version as now it will come from the Quarkus Extension and be brought in transitively.

**Comment by ia3andy** [comment]
@shivam-sharma7 where are you with this, this is an important update, I will make a release later today, if you can't make it by then I'll do it myself, it's a really easy change.

**Comment by shivam-sharma7** [comment]
@ia3andy I know only we need to remove old with this and replace some imports. But why this is taking so much time to compile in my machine I have already mention some error-https://github.com/quarkiverse/quarkus-quinoa/issues/474

**Comment by shivam-sharma7** [comment]
And it will take some time so you can do this.

**Comment by ia3andy** [comment]
@shivam-sharma7 I will put you maintainer status on hold (you keep your contributor badge) until you figure all this out. It is important as a maintainer to be able to build the project locally, review PRs and add features. 
PRs with just linting stuff or version update can be achieved by bots. I would advise you to look for good-first-issue around coding (not just docs) on the Quarkus eco-system and try to solve them by yourself with as little question and help as possible. When you believe you are ready to be a maintainer, I'll give you another issue to confirm and we can re-evaluate this!
