### ISSUE TITLE
Support yarn 2.x+ (berry)

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#521]
We need to make sure we have detection for it (the lockfile is different). I believe package manager install is not yet supported by the Maven Frontend Plugin core.

**Comment by melloware** [comment]
Definitely looks like an open issue: https://github.com/eirslett/frontend-maven-plugin/issues/1097

**Comment by ia3andy** [comment]
@melloware the flag is just for running, for running we don't use Maven Frontend Plugin (just for installation which don't support berry)
