### ISSUE TITLE
Better way to decide if we should install packages and build

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#526]
Currently we install depending on if the node_modules directory exists (unless `quarkus.quinoa.force-install=true`), this was an easy solution to get started but I guess we can do better.

Idea:
- have a layered quinoa target directory `target/quinoa/build`
- copy the package.json in the `target/quinoa`  (after install is successful)
- check for changes between build to trigger install (install if it doesn't exists)

This way when `clean` is done it will re-install
We could also compute some efficient hash of relevant files and put it in target/quinoa to avoid rebuilding all the time

**Comment by melloware** [comment]
i like this idea.  I will take a shot at this one.

**Comment by ia3andy** [comment]
@melloware have a look at the zulip discussion I pinged you on it might help
