### ISSUE TITLE
SvelteKit is not supported (add to doc)

### ISSUE THREAD

**Issue by steffenvan** [quarkiverse/quarkus-quinoa#547]
EDIT: changed `webui/src/routes/+page.svelte` -> `webui/src/app.html`

I've encountered some difficulties while trying to integrate SvelteKit and Quarkus with Quinoa. I would like some guidance. But ultimateIy, I believe the root of the problem comes from insufficient documentation that shows the necessary steps for an easy setup.

For instance under the "web-frameworks" tab, under the Svelte row, it recommends to use the official SvelteKit installation: 

```
npm create svelte@latest myapp
```

while it should rather be: 

```
npm create svelte@latest webui
```
as Quinoa seems to expect the UI component to have that name. 

Afterwards: 
```
cd webui
npm install
```
And trying to start the server with `quarkus dev`, I would expect that accessing `localhost:8080` would display the content of `webui/src/app.html`, but it shows me the default quarkus dev ui. If there are additional necessary configurations I think it would be helpful to know what those are in the guide. 

For context, my `application.properties` does contain:
```
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
```
which is the default server port for SvelteKit. 
Besides this there are probably additional things. But already, I think these steps should be documented a bit more clearly.

**Comment by steffenvan** [comment]
Okay great thanks. So what are the steps to be able to do that with an existing quarkus project? Because it seems that it won't do this with the setup described in the documentation.

**Comment by melloware** [comment]
so you already have a Quarkus project you are not starting a new one?

What I do is this..

1. Add the Quinoa 2.2.1 to your pom.xml
2. Add your web project to `/src/main/webui`

that is it.  Quinoa should auto-detect it all it runs `npm install` if it see your package.json has changed or is brand new etc.

**Comment by steffenvan** [comment]
So if I do the same setup as I described before, where I start a new quarkus project like this

```quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa```

delete the webui folder, and create a new one as before. I'm wondering why it still displays the default quarkus ui?

**Comment by melloware** [comment]
Can you compare your project to my working project and see what is different?

**Comment by melloware** [comment]
Interesting as how does the app know to start without an index.html?  How does it know to load main.js and run the page?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Svelte</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

**Comment by ia3andy** [comment]
@steffenvan  you need to remove `src/main/resource/META-INF`

**Comment by ia3andy** [comment]
@melloware  maybe we should add this to the doc?

**Comment by melloware** [comment]
Agreed I marked it  documentation ticket.  @steffenvan do you want to submit another PR mentioning the remove /src/main/resources/META-INF step?

**Comment by steffenvan** [comment]
> Interesting as how does the app know to start without an index.html?

I think it's because quarkus will look into `src/main/resource/META-INF` and try to load an html file from there.

@ia3andy Do you mean the folder entirely? I thought that whatever quinoa loads would have priority over what's in that folder, as written in bottom of the page of: https://docs.quarkiverse.io/quarkus-quinoa/dev/index.html

```
With Quinoa, you don’t need to manually copy the files to META-INF/resources. Quinoa has its own system and will provide another Vert.x route for it. If you have conflicting files with META-INF/resources, Quinoa will have priority over them.
```

**Comment by melloware** [comment]
@steffenvan it does.  I think that is why my project has an index.html mine is winning.  Yours does not have one to override so the /META-INF is winning.

**Comment by ia3andy** [comment]
Ah right, I forgot, you are right @steffenvan, Quinoa has priority over META-INF, sorry I mixed things up.


Yeah I believe vite require an index.html to work.

**Comment by steffenvan** [comment]
It seems like adding an `index.html` file to `webui/` isn't sufficient. It seems like there is additional things we need to do?

**Comment by steffenvan** [comment]
Btw @melloware please let me know if this was intended, but the example you gave was a basic building block for a Vite + Svelte build. In the README, it gives a couple (not so detailed) reasons why using that tech stack would be preferable over SvelteKit. But for simplicity, I think it makes sense to support an official stack, like SvelteKit. 

So I kinda lost the thread a little, do you guys know what is needed to make it possible to integrate SvelteKit into a project with Quinoa? Both from scratch using: 

`quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa` and into an existing one? In any case, I think it would make sense to add  an option to choose a web framework with the Quarkus CLI. Currently, I have to manually remove the `webui` that comes with the above command and call 
```
npm create svelte@latest webui
```
afterwards which is a little nuisance. I'm also not sure this is the right  way to do it.

**Comment by melloware** [comment]
I will have to try it. It should be possible if it's just a Node application.

**Comment by melloware** [comment]
Also with the wide world of the node system it would be way too much work for us to keep on top of every framework for the starter. I use React + Vite and it works out of the box for me.  SvelteKit is something that if it doesn't have and index.html would have to figure out how quinoa can call it. 

As always PR's are welcome!!

**Comment by steffenvan** [comment]
Yeah it's difficult to keep things up to date. Especially since it seems like it's mostly the two of you doing the majority of the work - thanks for that either way! 

@ia3andy So SvelteKit create `webui/src/app.html` which I guess we can use a surrogate for the expected `index.html`. However, Quinoa seems to not overwrite the `META-INF/index.html` when accessing `localhost:8080`. 

Just want to note that accessing `localhost:5173` does work.

**Comment by steffenvan** [comment]
I'm no SvelteKit expert, but I'm pretty sure it's not uncommon to use another backend with SvelteKit. For instance, if your code needs to do some complicated business logic. Then it would still be nice to have all the routing capabilities from SvelteKit in the project. 

While the default for it is that SSR to be enabled, it can easily be disabled. So I'm not sure that is the main issue. 

Correct me if I'm wrong, but it seems that **Quinoa** also expects `webui/index.html` to be present? And is there some logic in the code going on that prevents it from detecting it, even if that file is present when we create a new SvelteKit project? That sparks a related question: what actually prevents Quinoa from working with SvelteKit?

**Comment by ia3andy** [comment]
> I'm no SvelteKit expert, but I'm pretty sure it's not uncommon to use another backend with SvelteKit. For instance, if your code needs to do some complicated business logic. Then it would still be nice to have all the routing capabilities from SvelteKit in the project.

Routing = server

> 
> While the default for it is that SSR to be enabled, it can easily be disabled. So I'm not sure that is the main issue.

Then what's the point of using SvelteKit vs Vite

> 
> Correct me if I'm wrong, but it seems that **Quinoa** also expects `webui/index.html` to be present? And is there some logic in the code going on that prevents it from detecting it, even if that file is present when we create a new SvelteKit project? That sparks a related question: what actually prevents Quinoa from working with SvelteKit?

Because it would only work in devmode, because devmode actually starts the server, in production, the server is only Quarkus.

**Comment by steffenvan** [comment]
> Routing = server

If we were using React instead of SvelteKit and ran: 
```
npm install react-router-dom
```
I think we wouldn't call it a server? Either way, related to the issue we had before, if we follow the Quinoa guide and try to create our frontend with React:

```
npx create-react-app webui
```

there isn't a `webui/index.html` file. It's located under `webui/public/index.html`. So this shouldn't be a problem for SvelteKit?  In the official Quinoa guide it says that this is configurable but doesn't state how. May I ask where/how we can do that? 

> Then what's the point of using SvelteKit vs Vite

Taken from SvelteKit's own tutorial: 

- Routing
- ~~Server-side rendering~~
- Data fetching
- Service workers
- Prerendering
- Single-page apps
- Library packaging
- Optimised production builds
- Deploying to different hosting providers
- ...and so on

Vite probably offers a lot of these things, but the fact that we get them out of the box seems pretty neat to me.

**Comment by melloware** [comment]
@steffenvan a few things.

1. Here is a fully working Create React App even using Postgres DB and real REST Services in a PrimeReact UI: https://github.com/melloware/quarkus-monorepo

2. Yes it is in `/public/index.html` but when you run `npm run start` which is what Quinoa does then Create React app serves the index.html out of `public`  as `/index.html`  So when Vert.X asks for `index.html` the Quinoa one wins because its truly being served in the same location as /src/META-INF/index.html.

3. This diagram explains what is happening: https://docs.quarkiverse.io/quarkus-quinoa/dev/main-concepts.html#_runtime_for_production_mode

![image](https://github.com/quarkiverse/quarkus-quinoa/assets/4399574/511af8a3-ecfa-4398-861b-80d72b73f558)

So in my Vite + Svelte example there is an index.html to be intercepted and return a 200OK where in SvelteKit it is server its own data and clearly not responding 200 OK to its index.html or however it is serving its app?

**Comment by melloware** [comment]
So long story short you need a way for SvelteKit to respond when `index.html` is requested that it returns a 200OK else it won't work.

**Comment by ia3andy** [comment]
> > Routing = server
> 
> They are two different, but not completely distinct concepts. If we were using React instead of SvelteKit and added routing to React:
> 
> ```
> npm install react-router-dom
> ```

> 
> I think we wouldn't call it a server? Either way, related to the issue we had before, if we follow the Quinoa guide and try to create our frontend with React:
> 
> ```
> npx create-react-app webui
> ```
This is browser routing which is totally different and does not require a server.

If you want browser routing with Svelte, go for something like this (compatible with Quinoa): https://www.makeuseof.com/svelte-routing-introduction/

**Comment by ia3andy** [comment]
SvelteKit per Design can't be supported by Quinoa because it's a server. There is no discussion since it is not an option.

If you want to use SvelteKit, then you need to have two services, one with Quarkus and one with SvelteKit and call the Quarkus one through Rest.

**Comment by ia3andy** [comment]
Here is something you could explore: https://github.com/sveltejs/kit/tree/master/packages/adapter-static

**Comment by ia3andy** [comment]
> Here is something you could explore: https://github.com/sveltejs/kit/tree/master/packages/adapter-static

@steffenvan if you manage to make this work 👆, you can add it to the documentation.

**Comment by ia3andy** [comment]
@melloware maybe we should state in the doc, that Quinoa is only working with NodeJs frameworks which generate static sites.

BTW it could be cool to have Gatsby example which would mix static blog generation and Quarkus for the dynamic parts (comments, ...).

**Comment by melloware** [comment]
Agreed I will look at updating the docs and I will open a ticket for a Gatsby example!

**Comment by steffenvan** [comment]
Thanks a lot for the clarifications guys, it was very helpful!

**Comment by treo** [comment]
> SvelteKit per Design can't be supported by Quinoa because it's a server. There is no discussion since it is not an option.

That isn't quite true. SvelteKit can also be used to create a serverless SPA. You obviously lose the SSR benefits and server side functionality, but I've used it in SPA mode just fine. 

It only needs one thing from the server that is serving it in SPA mode: If something is requested that isn't actually a file, it should serve the index.html file. 

See https://kit.svelte.dev/docs/single-page-apps#usage and the section about configuring Apache that follows.

**Comment by melloware** [comment]
@treo awesome stuff!  Do you want to submit a PR updating the Frameworks doc for SvelteKit with this info?

**Comment by treo** [comment]
Sure, I can do that. I guess I'll have to double check if removing the pre-existing META-INF folder is even necessary.

**Comment by melloware** [comment]
@treo much appreciated in advance!
