### ISSUE TITLE
Add some control over the dev-server from the dev-ui

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#55]
🚀🚀🚀

**Comment by ia3andy** [comment]
@melloware it would be nice if we could add some control over the dev server in the dev-ui:
- have the ui logs
- run install and restart
- restart

**Comment by melloware** [comment]
Love these ideas.  I will take a look if you want to assign this ticket to me!

**Comment by melloware** [comment]
OK I got the PackageManager Install working but I am having trouble getting the stopDev and start working because if I try and pass the ForwardDevBuildItem to the UIProcessor I am getting a "Chained Build Exception".

**Comment by ia3andy** [comment]
@melloware 

A possible workaround for the restart (and restart after install) would be to find a way to trigger a refresh like when there is a config change, this restarts the dev server again. 

If you can find a way to do that, you may do a PM install and then restart (I don't think it's a problem to keep the process running during the install and restart after).

**Comment by melloware** [comment]
Awesome let me try that.

**Comment by melloware** [comment]
OK just for fun I tried this...

```java
    @BuildStep(onlyIf = IsDevelopment.class)
    HotDeploymentWatchedFileBuildItem watchLockFile(QuinoaConfig quinoaConfig, OutputTargetBuildItem outputTarget) {
        final ProjectDirs projectDirs = resolveProjectDirs(quinoaConfig, outputTarget);
        final Path packageFile = projectDirs.uiDir.resolve("package-lock.json");
        return new HotDeploymentWatchedFileBuildItem(packageFile.toString());
    }
```

And when I do an `install` that changes the package-lock.json and I see this in the log

```
2023-03-27 13:11:18,174 INFO [] (executor-thread-1) File change detected: C:\dev\quarkus\nextjs\src\main\webui\package-lock.json
2023-03-27 13:11:18,174 INFO [] (executor-thread-1) Restarting quarkus due to changes in package-lock.json. 
```

But I don't see the ForwardDevProcessor actually stop and restart which I thought it would.

**Comment by ia3andy** [comment]
@melloware try this:
```java
public HotDeploymentWatchedFileBuildItem(String location, boolean restartNeeded) {
        this.location = location;
        this.restartNeeded = restartNeeded;
    }

**Comment by melloware** [comment]
OK yeah I had some extra code I think its working now.
