### ISSUE TITLE
Create a branch for 2.2.x 

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#595]
As 2.2.x is targeting Quarkus 3.2 (LTS) we should have a branch for it.

Also there are a few important PRs that should be backported https://github.com/quarkiverse/quarkus-quinoa/labels/backport-2.2.x
and released

@melloware are you taking this one?

**Comment by melloware** [comment]
Yes I will do this today.

**Comment by ia3andy** [comment]
Thanks @melloware you rock!!!!
