### ISSUE TITLE
Option for specifying additional watch locations

### ISSUE THREAD

**Issue by TeHMoroS** [quarkiverse/quarkus-quinoa#61]
Hi. I'm using Quarkus nad Quinoa to create a HDA (hypermedia-driven application) using Htmx-proposed approach (TL;DR - I return parts of HTML code instead of JSON, which Htmx uses to update the page). Quarkus has a nice templating solution (Qute) and now Quinoa is a cherry on top. :) The approach uses Quarkus+Qute for generating HTML and Quinoa+Webpack for generating other assets (images, fonts, CSS, etc.).

One point in the workflow is PurgeCSS, which removes any unnecessary CSS that is not present in the templates. The setup works quite well, until I update any of the templates. Quarkus will detect the change, but Quinoa won't, because the templates are in a seperate directory (`src/main/resources/templates` for Qute vs `src/main/webui` for Quinoa).

It would be nice to specify additional watch locations in Quinoa's configuration, to have a little more power over when the UI build is triggered. It could be a list of globs, regular expressions or a simple directory list.

The current workaround is to restart the Quarkus dev mode, triggering Quinoa in the process, which is not that bad at this point (a few seconds), but will probably grow in the future.

**Comment by ia3andy** [comment]
Hi @TeHMoroS, thanks for your feedback!

This is an interesting use-case, could you prepare some kind of light reproducer I could see to understand exactly the issue.

Regards,

**Comment by TeHMoroS** [comment]
Hello, @ia3andy.

I've created a simple project reproducing the issue in question. It's a bare minimum setup (going all out with Htmx and other things would take a little longer):
- Quarkus + RestEasy Reactive + Qute
- Quinoa
- WebPack + plugins for handling CSS: a CSS extractor and PurgeCSS.

I've put all the details in the README file: https://github.com/TeHMoroS/quinoa-watch-issue

Regards.

**Comment by ia3andy** [comment]
Thanks for creating this :) I am in PTOs for two days, I will have a look on monday..

**Comment by TeHMoroS** [comment]
Hi @ia3andy.

It is a quite specific use case, not too popular yet. :)

While I see your point in reading the unprocessed template not being a good practice (it really isn't when the workflow's a bit more complex), it's should fine if you only use it for the purpose of purging unwanted CSS (PurgeCSS by default reacts to any words found in the template, even HTML comments, not patterns like, let's say, `class="..."` as Tailwind does by default).

Allowing Quinoa to trigger on manually chosen resources would allow to make such use cases without workarounds, but the whole approach is quite niche for the time being (maybe we'll get a surge in Htmx/HDA popularity some time in the future, fingers crossed). In the end I used a different workaround: I've disabled PurgeCSS in DEV mode via Webpack (it has a valid reason: you might want all styles in DEV mode). It still removes unnecessary CSS rules in PROD, so I guess we achieved the desired effect.

Thank you for your time. :)

**Comment by ia3andy** [comment]
> Hi @ia3andy.
> 
> It is a quite specific use case, not too popular yet. :)
> 
> While I see your point in reading the unprocessed template not being a good practice (it really isn't when the workflow's a bit more complex), it's should fine if you only use it for the purpose of purging unwanted CSS (PurgeCSS by default reacts to any words found in the template, even HTML comments, not patterns like, let's say, `class="..."` as Tailwind does by default).
> 

Ok 👍

> Allowing Quinoa to trigger on manually chosen resources would allow to make such use cases without workarounds, but the whole approach is quite niche for the time being (maybe we'll get a surge in Htmx/HDA popularity some time in the future, fingers crossed).

If we have a popular use-case, for sure we should add it but for the time being YAGNI 🤪

> In the end I used a different workaround: I've disabled PurgeCSS in DEV mode via Webpack (it has a valid reason: you might want all styles in DEV mode). It still removes unnecessary CSS rules in PROD, so I guess we achieved the desired effect.

Yeah that makes sense, I am glad you found a solution :)

> 
> Thank you for your time. :)

YW

FYI 1.0.4 (released but not yet in Maven Central) will change a bit Quinoa behavior as it will have priority over the META-INF/resources, but in your case it shouldn't change anything.

**Comment by ia3andy** [comment]
@TeHMoroS I would be interested in discussing Htmx/HDA with you, I am sure we could find a really integrated user experience with Qute/Renarde/Quinoa and HDA

**Comment by TeHMoroS** [comment]
@ia3andy No problem. I've sent you an e-mail to the address in your profile.
