### ISSUE TITLE
Authentication for downloading Node from private registry

### ISSUE THREAD

**Issue by stevenfuhr** [quarkiverse/quarkus-quinoa#614]
### Describe the bug

Since https://github.com/quarkiverse/quarkus-quinoa/pull/513 it is no longer possible to download Node or NPM from private registries that require authentication.

Before I was able to use basic authentication parameters by setting quarkus.quinoa.package-manager-install.node-download-root to 
https://user:api-key@example.org/dist/

There's no other authentication implementation present either in https://github.com/quarkiverse/quarkus-quinoa/blob/04d0dc9edce9b4123e7a2f0c0b8864ba795a295e/deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java#L39-L69

### Quinoa version

2.2.0

### Quarkus version

3.6.5

### Build / Runtime

Angular

### Package Manager

NPM

### Steps to reproduce the behavior

1. Create a new Quinoa (2.2+) project
2. Try downloading from a private registry as described above

### Expected behavior

Not breaking the only possible authentication method

**Comment by ia3andy** [comment]
Hello @stevenfuhr,

Thanks for reporting this, it is indeed an issue that needs to be fixed.

Would you provide a PR for it?

Cheers,

**Comment by genzarchitect** [comment]
I would love to work on this. Can you assign it to me

**Comment by melloware** [comment]
@genzarchitect assigned to you!

**Comment by genzarchitect** [comment]
Could you please give me come starting points @melloware

**Comment by genzarchitect** [comment]
@melloware Could you please let me know the steps how can i run this so that i can test weather it is working or not

**Comment by melloware** [comment]
Run "mvn clean install -Dmaven.test.skip" which will build 999-SNAPSHOT version

Then in your project use version 999-SNAPSHOT

**Comment by stevenfuhr** [comment]
@genzarchitect You could simply serve the node archive from your local filesystem using some server with basic authentication enabled.

I could also propose a solution if you're not already in too deep with your implementation 😃

**Comment by melloware** [comment]
Thanks @stevenfuhr !

**Comment by stevenfuhr** [comment]
@genzarchitect I've created a PR https://github.com/quarkiverse/quarkus-quinoa/pull/615
Maybe you want to take a look at it.

**Comment by melloware** [comment]
Sonatype is currently down.  I will attempt to deploy again when its back up.

**Comment by stevenfuhr** [comment]
@ia3andy @melloware Thanks for the quick merge and release :)

**Comment by melloware** [comment]
Thanks for the PR!
