### ISSUE TITLE
Be able to generate client from openapi specification for build

### ISSUE THREAD

**Issue by dcdh** [quarkiverse/quarkus-quinoa#631]
## Feature idea

Following this project https://github.com/dcdh/formula-interpreter/blob/master/pom.xml
the _openapi-generator-maven-plugin_ is used to generate client in typescript based on openapi yaml file produce by the _quarkus-smallrye-openapi_ dependency.

The build is done this way:
1. build openapi yaml
2. generate typescipt client using openapi-generator-maven-plugin at prepare-package phase
3. Just after build the project using frontend-maven-plugin also at prepare-package phase

Regarding quinoa, building the openapi.yaml and the project is done in only one phase at build one. So I am not able generate my typescript client after openapi.yaml generation and before building the project.

So it will be nice if it was possible split the build into two: build for backend services and prepare-package for frontend one with the ability to do something between them (like code generation).

Regards,
Damien

**Comment by melloware** [comment]
I understand what you are saying. I use Orval to generate my TypeScript for React Query from OpenApi right now I just do it as 2 steps.  Generate the OpenApi JSON then I copy that to my webui and run `npm run codegen`

**Comment by dcdh** [comment]
I am using it using this kind of configuration:

application.properties:
```properties
quarkus.smallrye-openapi.store-schema-directory=src/main/webui/
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
```

package.json
```json
{
// ...
  "scripts": {
    "dev": "orval --config ./orval.config.ts && react-scripts start",
    "build": "orval --config ./orval.config.ts && react-scripts build",
    "test": "react-scripts test --env=jsdom"
  },
// ...
}
```

This way endpoints are generated add dev starting and build stages. No need to generate next copy to webui

**Comment by melloware** [comment]
Wow this is awesome!  Going to try it tomorrow!

**Comment by melloware** [comment]
@dcdh ok i am adding this to the docs for other people in the future.

**Comment by dcdh** [comment]
Hello @melloware 

could you update the documentation please.

This way is more convenient because openapi.json and yaml should not be present in production code

```application.properties
quarkus.smallrye-openapi.store-schema-directory=target
```

```orval.config.ts
import { defineConfig } from 'orval';

// generate only for front tagged endpoints
export default defineConfig({
    front: {
        output: {
            mode: 'split',
            target: 'src/api/endpoints.ts',
            schemas: 'src/api/model',
            prettier: true,
            override: {
                mutator: {
                    path: 'src/api/mutator/custom-instance.ts',
                    name: 'customInstance',
                },
            }
        },
        input: {
             target: './../../../target/openapi.yaml',
        },
    },
});
```

**Comment by melloware** [comment]
hmmm not sure i agree with this?   I leave mine there so people can `curl` the openapi.yml file and generate their remote stubs with it.  Plus it checks it into Git which gives me a traceability of changes if someone reports a bug i can see the open API spec history.

So I think this might be a matter of preference?
