### ISSUE TITLE
Add an option to select where to store generated build files

### ISSUE THREAD

**Issue by dcdh** [quarkiverse/quarkus-quinoa#636]
## Feature idea

Currently, the build is generated inside `target/quinoa` directories.

Would it be possible to add an option to select the directory where the build files should be generated likes `target/classes/META-INF/resources/other_unexistant_path_name`

**Comment by melloware** [comment]
This is a good first issue for someone...

**Comment by dcdh** [comment]
I prefer closing up because it is already do able by using the ui-dir referencing directly the src/main/ressources/META-INF/ressources/my_folder I forger about it.

**Comment by ia3andy** [comment]
@dcdh well, I don't think you should do this, the `src/main/ressources/META-INF/ressources/` is meant for static file, this could lead to really strange behaviours..

Could you explain your purpose (if it's not serving which is already covered by Quinoa)?

**Comment by dcdh** [comment]
Yes, sorry I misunderstood.

Currently, with this configuration:
```properties
quarkus.quinoa.build-dir=build
```
the build will be inside `target\quinoa\build`
and I would like to be inside `target\classes\META-INF\resources\my_custom_folder`

What is inside `my_custom_folder` should be served by Quarkus.
Next the purpose is to package my application inside another application called as a monolith application.
This is what I have done regarding backend here : https://github.com/dcdh/photo-gallery-monolith but regarding for frontend.

So my monolith should be able to access the packaged application this way http://localhost:8080/my_custom_folder

I've already done it serving only index.html file and it works likes a charm.

**Comment by ia3andy** [comment]
Ok I think you are looking to it the wrong way, you should have to set the build-dir for this. I guess this is what you are looking for: https://github.com/quarkiverse/quarkus-quinoa/issues/302

**Comment by ia3andy** [comment]
Build Dir is meant for a different purpose, it is the directory used by the Framework when generating the files: https://docs.quarkiverse.io/quarkus-quinoa/dev/config-reference.html#quarkus-quinoa_quarkus.quinoa.build-dir

**Comment by ia3andy** [comment]
Again, there is no point of changing the `targetBuildDir`. Everything is handled by Quinoa (serving and all). If you are looking for a sub-path this should be handled by Quinoa.

**Comment by ia3andy** [comment]
Ok I think I get why you are trying to go this way, it's because you want to mimic what's done with your other resources (that you get from the artifacts). 

Quarkus (and Quinoa) is not meant for creating "packages", it is meant to create applications, you can create libraries using extensions or jandex but this is another topic.

My suggestion is:
- Have a look to the https://github.com/eirslett/frontend-maven-plugin which is what you are looking for to build you app and create an artifact from it
- Use Quarkus as you mentioned with `unpack-dependencies`


Another option, have a look at how this done for code.quarkus.io using the Web Bundler which might be a better fit: 
https://github.com/quarkusio/code.quarkus.io

**Comment by ia3andy** [comment]
@melloware wdyt?

**Comment by melloware** [comment]
@ia3andy i think you are right.  I still don't fully understand the use case. Trying to wrap my brain around it but if he is trying to use quarkus as a package and not an app then yet I agree with all of your suggestions to try.  I don't think this is something that should be tweaked in Quinoa.

That being said would having a config for the build directory hurt?  Probably not...but even then would it still solve this use case?

If it does I can add the config if you want?

**Comment by ia3andy** [comment]
> @ia3andy i think you are right. I still don't fully understand the use case. Trying to wrap my brain around it but if he is trying to use quarkus as a package and not an app then yet I agree with all of your suggestions to try. I don't think this is something that should be tweaked in Quinoa.
> 
> That being said would having a config for the build directory hurt? Probably not...but even then would it still solve this use case?
> 
> If it does I can add the config if you want?

I believe it could lead to all sorts of mistakes or misuse. Currently, anyone can use the target directory with some maven plugin to do whatever with it.

**Comment by dcdh** [comment]
Hello,

I've finally managed to done it this way

```xml
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <configuration>
                            <target>
                                <mkdir dir="${basedir}/target/classes/META-INF/resources" />
                                <copy todir="${basedir}/target/classes/META-INF/resources">
                                    <fileset dir="${basedir}/target/quinoa/build" includes="**" />
                                </copy>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>quinoa</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

By using a classifier I can produce expected package without changing the existent.

I did not notice that `jar:jar` is running before build... I do not know why because it should be run during the package phase.

Thanks a lot to both of you. Regards, Damien
