### ISSUE TITLE
Serve only option

### ISSUE THREAD

**Issue by mschorsch** [quarkiverse/quarkus-quinoa#644]
Please provide an option to only serve a prebuild js app.

See discussion https://github.com/quarkiverse/quarkus-quinoa/discussions/643

**Comment by ia3andy** [comment]
Quarkus is already able to serve static files out of the box (see https://quarkus.io/guides/http-reference#from-the-application-jar)

With Gradle, just copy the built files over to `build/generated/resources/META-INF/resources` 


You need this in the build.gradle:
```groovy

sourceSets {
    main {
        resources {
            srcDir "${buildDir}/generated/resources"
        }
    }
}
``` 


Quinoa is not needed for this..


Maybe we could add a section in the http reference guide to explain how to serve generated files.
