### ISSUE TITLE
Downloading Node with custom root

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-quinoa#647]
### Discussed in https://github.com/quarkiverse/quarkus-quinoa/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **RiverOmega** March  1, 2024</sup>
Hello! 

The property `quarkus.quinoa.package-manager-install.node-download-root` allows me to download from a custom registry, which is nice. But Quinoa itself concatenates the root with `/{node-version}/node-{node-version}-linux-x64.tar.gz`, and I can't seem to find a way to change this, because that is not how things are structured in the registry I'm working with.

Is there any workaround to this? In my case I have:

`root/node-{node-version}.tgz`</div>

**Comment by melloware** [comment]
@RiverOmega this is a good first issue if you want to investigate it!

**Comment by RiverOmega** [comment]
I'll try to take a look in the coming days, currently swamped. Thanks for the mention, it is indeed a good first issue 👍

**Comment by melloware** [comment]
@RiverOmega it actually looks like this comes from `com.github.eirslett.maven.plugins.frontend.lib` the Frontend Maven Plugin lib.

**Comment by melloware** [comment]
OK I am gonna close this ticket. I agree they should follow conventions!
