### ISSUE TITLE
Static files not copied in GitlabCI

### ISSUE THREAD

**Issue by mbouhda** [quarkiverse/quarkus-quinoa#648]
### Describe the bug

Discussed in [Zulip ](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quinoa.20generates.20a.20build.20file.20instead.20of.20a.20directory).
In GitlabCI, the packaged jar doesnt contain frontend static files, while it works fine locally in a windows machine.
We found the culprit in _prepareBuiltResources_ method of _QuinoaProcessor_, which does a **Files.walk**(targetDir) resulting in a call to **walk**(start, Integer.MAX_VALUE, options) without _options_.

In **walk**(start, Integer.MAX_VALUE, options) javadoc it is mentionned that:
> By default, symbolic links are not automatically followed by this method. If the options parameter contains the FOLLOW_LINKS option then symbolic links are followed.

Can you fix this please?
Thanks!

### Quinoa version

2.3.4

### Quarkus version

3.7.4

### Build / Runtime

Other

### Package Manager

PNPM

**Comment by melloware** [comment]
PR Submitted.

**Comment by melloware** [comment]
Ok new version is released can you test it?
