### ISSUE TITLE
Routing does not work with RestEasy Classic

### ISSUE THREAD

**Issue by fasuke85** [quarkiverse/quarkus-quinoa#66]
Hi,
I have generated a starter-project with Quinoa (v 1.0.3) and Resteasy Classic (2.9.2.Final), when i go to /quinoa.html I get an 404-error. If I only use Quinoa in the project it works as expected.

**Comment by chriscohnen** [comment]
Most likely UI will need some business logic. So interacting with rest in backend would be good.

I also get a 404 - Resource Not Found , on quarkus web port  which shows "REST resources" and "Additional endpoints"
 but I would like to see content from an index.html (served from a vue.js frontend in my case)
the frontend is only reachable on configured dev-server-port.
could be the same problem I have as the one reported. Or I just messed up my config, also possible.

Would be really great if somebody could check above problem!

**Comment by ia3andy** [comment]
Hi @fasuke85 @chriscohnen, I will give it a try today. In the meantime, could you try with resteasy reactive?

**Comment by ia3andy** [comment]
Ok this is a big bug, I will find a fix quickly.

**Comment by ia3andy** [comment]
I've found a solution, I will do a release soon.

**Comment by ia3andy** [comment]
I've provided a PR to fix this https://github.com/quarkiverse/quarkus-quinoa/pull/68
@chriscohnen @fasuke85 if you want to give it a try, you have to build locally and use `999-SNAPSHOT`.

**Comment by ia3andy** [comment]
```bash
quarkus create app quinoa-resteasy -x=io.quarkiverse.quinoa:quarkus-quinoa:999-SNAPSHOT -x=resteasy
```

**Comment by ia3andy** [comment]
@chriscohnen @fasuke85  1.0.4 is available with the fix :)
