### ISSUE TITLE
SPA: Resuming on 404

### ISSUE THREAD

**Issue by ThoSap** [quarkiverse/quarkus-quinoa#665]
Just as a heads up, could Quinoa be refactored to use
https://github.com/quarkusio/quarkus/pull/38852
when
`quarkus.quinoa.enable-spa-routing` is enabled?

**Comment by ia3andy** [comment]
It's already the case, it's done using BuildItems

**Comment by ia3andy** [comment]
https://github.com/quarkiverse/quarkus-quinoa/blob/main/deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java#L265

**Comment by ThoSap** [comment]
All good then 😋
I just thought that Quinoa could maybe use the refactoring of this PR which is for Quarkus REST (formerly Quarkus RESTEasy Reactive).

**Comment by melloware** [comment]
Closing this as I don't think there is any action for us. Will reopen if anyone disagrees
