### ISSUE TITLE
Change Logo and Description

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#667]
The idea is to move from Quarkus + NodeJS to "Quarkus + npm-compatible apps". NodeJS being a server, could be confusing to users.

Description:
Develop, build, and serve your npm-compatible web applications such as React, Angular, Vue, Lit, Svelte, Astro, SolidJS, and others alongside Quarkus.

Any thoughts?

**Comment by ia3andy** [comment]
cc @holly-cummins

**Comment by melloware** [comment]
Agreed we should do this....but I also opened this: https://github.com/quarkiverse/quarkus-quinoa/issues/564

Thoughts?

**Comment by holly-cummins** [comment]
I think your proposed description is good.

**Comment by melloware** [comment]
OK PR coming.  Dev Card now looks like this...

![image](https://github.com/quarkiverse/quarkus-quinoa/assets/4399574/0f47f406-e4ce-49f0-8025-65ddfdab3085)

**Comment by holly-cummins** [comment]
https://quarkus.io/extensions/io.quarkiverse.quinoa/quarkus-quinoa/ has picked up the change:
<img width="218" alt="image" src="https://github.com/quarkiverse/quarkus-quinoa/assets/11509290/7d27447e-5dc2-4462-a0d5-e7b1a0b6fafa">
