### ISSUE TITLE
Vite compatibility - Forwarding to root

### ISSUE THREAD

**Issue by adamhenderson** [quarkiverse/quarkus-quinoa#67]
Have noticed a minor issue when using vitejs to bootstrap a project.

quinoa is not forwarding on to the vite server for calls to http://localhost:8080 (root) resulting in a Resource not Found message, however http://localhost:8080/index.html does resolve correctly, odd since vite server responds to http://localhost:3000 so unclear why the app is not forwarding to the dev server for root.

http://localhost:8080 -> Resource not found
http://localhost:8080/index.html -> ok
http://localhost:3000 -> ok

When the app is built it all works perfectly, just the dev mode has the issue.

When testing against the default quinoa quickstart, quinoa does indeed work as expected forwarding the request to the dev-server so http://localhost:8080 responds with the Theater app.

Have included a simple reproducer https://github.com/adamhenderson/quinoa-vite-reproducer

**Comment by ia3andy** [comment]
I will have a look today ;-) Thanks for reporting!

**Comment by ia3andy** [comment]
I am pretty sure that #68 will fix this, @adamhenderson would you give it a try, you need to clone quinoa, then: `mvn clean install -DskipTests` and then use `999-SNAPSHOT`.

**Comment by ia3andy** [comment]
I will do a release later today.

**Comment by ia3andy** [comment]
I am closing this issue as it is fixed on the main branch

**Comment by ia3andy** [comment]
Also worth mentioning: https://github.com/quarkiverse/quarkus-quinoa/issues/71

**Comment by ia3andy** [comment]
@adamhenderson 1.0.4 is available with the fix :)
