### ISSUE TITLE
EcoSystem CI Build Failing

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-quinoa#670]
Quinoa is failing the nightly build against the latest SNAPSHOT: https://github.com/quarkiverse/quarkus-quinoa/actions/runs/8626264166

**Comment by melloware** [comment]
@ia3andy can you subscribe to this ticket please: https://github.com/quarkiverse/quarkiverse/issues/211#issuecomment-2049020743

That lets you know when the nightly SNAPSHOT build of Quarkus fails with Quinoa!

**Comment by ia3andy** [comment]
Weird I've tried to reproduce the issue locally but all the test passes (you need to build core with `-Prelocations`), @melloware could you give it a try?

**Comment by melloware** [comment]
@ia3andy agreed I am stumped by this failure.  I am just not seeing it.
