### ISSUE TITLE
Allow to define if dev-server is HTTPS / TLS

### ISSUE THREAD

**Issue by ylemoigne** [quarkiverse/quarkus-quinoa#682]
## Feature idea
Currently, dev-server host and port are configurable.
But not the protocol. Please add support for https.

## Additional information
With the current situation :
If quarkus is used in https and angular is in http, the webapp will try to connect to `wss://host/ng-cli-ws` (and fail because ng serve is configured in http).
If quarkus is used in https and angular is in https, quinoa dev-server won't work.

**Comment by melloware** [comment]
@ylemoigne have you researched this at all? It seems like a good first issue for a PR!

**Comment by melloware** [comment]
@all-contributors add @ylemoigne for code

**Comment by melloware** [comment]
2.3.8 has been released and should be in maven central in the next hour

**Comment by ylemoigne** [comment]
Nice. Thanks you.
