### ISSUE TITLE
Solid-Start since before version 1.0.0 changed run scripts and CLI

### ISSUE THREAD

**Issue by apatrida** [quarkiverse/quarkus-quinoa#705]
### Describe the bug

The current code supports solid-start but using the old cli command, which has changed since they moved to be based on `vinxi` for the server support.  `solid-start dev` is now `vinxi dev` and other commands as well have changed.  You should create a solid-start project with 1.x and see the current scripts to update this project.

### Quinoa version

2.4.0

### Quarkus version

all

### Build / Runtime

Other

### Package Manager

OTHER

### Steps to reproduce the behavior

FrameworkType enum has 

```
SOLID_START(Set.of("solid-start dev"), generic("dist", "dev", 3000)), 
```

which is no longer correct since pre 1.0.0 versions (0.5.x maybe) of solid-start and not any after.

### Expected behavior

use `vinxi dev` instead of `solid-start dev`

**Comment by apatrida** [comment]
scripts generated in a new project are:

```
  "scripts": {
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start",
    "version": "vinxi version"
  },
```

and vinxi ports / bind host can be changed using `--port` and `--host` parameters:

``` 
vinxi dev --port 3300 --host 0.0.0.0
```

You can create a new project with:

```
npm init solid@latest
```
or for pnpm, bun, yarn, see https://docs.solidjs.com/solid-start/getting-started

Check the pacakge.json see the scripts and have a test project.  All create methods create the same package.json scripts.

**Comment by melloware** [comment]
PR submitted please review @apatrida
