### ISSUE TITLE
Update runtime diagram to reflect recent routing changes

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-quinoa#715]
Now, Quinoa is not in charge of the route to serve the static files anymore, this is done by Quarkus Http. This should be reflected in the doc: https://docs.quarkiverse.io/quarkus-quinoa/dev/main-concepts.html#_runtime_for_production_mode

Source is here:
https://github.com/quarkiverse/quarkus-quinoa/blob/main/docs/modules/ROOT/assets/images/quinoa-runtime-prod.excalidraw

**Comment by melloware** [comment]
@ia3andy i made the change but before I submit the PR can you verify this is correct?

![image](https://github.com/user-attachments/assets/f584d3df-f54c-4cc2-a1ab-bc9f13263ba8)

**Comment by melloware** [comment]
Or should I remove quinoa entirely from the diagram?

**Comment by ia3andy** [comment]
> Or should I remove quinoa entirely from the diagram?

Yes remove it and rename META-INF/resources by `Static Resources handler`
