### ISSUE TITLE
Quick start example fails to serve UI from production package.

### ISSUE THREAD

**Issue by dajester2013** [quarkiverse/quarkus-quinoa#763]
### Describe the bug

Using the latest Quarkus CLI + Quinoa, tried to set up the example app, but it fails to run correctly when packaged.

### Quinoa version

2.4.7

### Quarkus version

3.14.4

### Build / Runtime

Vite

### Package Manager

NPM

### Steps to reproduce the behavior

Used SDKMAN! to install the latest quarkus CLI, and configured a new project according to the README:
```
$ sdk install quarkus
....
$ quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa
-----------
selected extensions: 
- io.quarkiverse.quinoa:quarkus-quinoa

applying codestarts...
📚 java
🔨 maven
📦 quarkus
📝 config-properties
🔧 tooling-dockerfiles
🔧 tooling-maven-wrapper
🚀 quinoa-codestart

-----------
[SUCCESS] ✅  quarkus project has been successfully generated in:
--> [edited]/quinoa-app
-----------
Navigate into this directory and get started: quarkus dev
$ cd quinoa-app/
$ quarkus build
$ java -jar target/quarkus-app/quarkus-run.jar
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-09-17 07:47:40,938 INFO  [io.quarkus] (main) quinoa-app 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.14.4) started in 0.622s. Listening on: http://0.0.0.0:8080
2024-09-17 07:47:40,945 INFO  [io.quarkus] (main) Profile prod activated. 
2024-09-17 07:47:40,946 INFO  [io.quarkus] (main) Installed features: [cdi, quinoa, smallrye-context-propagation, vertx]
```

Navigate to localhost:8080/
![image](https://github.com/user-attachments/assets/86785ab7-504c-4798-82e5-85cf788feb3c)

### Expected behavior

Expected example app UI to be served.

**Comment by melloware** [comment]
Because it didn't want to interfere with the index.html that is already there don't you want the URL  http://localhost:8080/quinoa ???

That is where the CodeStart is serving from?

**Comment by dajester2013** [comment]
@melloware this is the production package, not the dev mode - according to the documentation, it is supposed to serve from http://localhost:8080

Even then, I get the same response from http://localhost:8080/quinoa

**Comment by melloware** [comment]
let me try it.

**Comment by melloware** [comment]
@ia3andy he is correct the Prod mode of the Code Start does not work.

**Comment by melloware** [comment]
@dajester2013 i see its served here http://localhost:8080/quinoa/

![image](https://github.com/user-attachments/assets/2dde8c08-1106-4799-b963-c08a001a63d6)

**Comment by dajester2013** [comment]
Roger that - can confirm.  I tried /quinoa, /quinoa.html, but not **/quinoa/**.  Dev mode serves from **/quinoa** btw.

**Comment by melloware** [comment]
Cool in normal scenario Not The CodeStart this all just works and serves from localhost:8080  we just do this special handling for /quinoa so we don't interfere with the index.html that may be from other extensions etc.
