### ISSUE TITLE
Is there the possibility of bringing to Flutter?

### ISSUE THREAD

**Issue by edufolly** [quarkiverse/quarkus-quinoa#78]
I know the extension is for node -based environments, but is there a possibility to bring to the flutter?

**Comment by ia3andy** [comment]
I've tried with React Native, it must be similar, my conclusion is that if you have a Quarkus backend for a mobile native app, then Quinoa can be nice if you also have a browser based app from it.. Else I don't really see the point:
- Quinoa can easily be configured to start the web app like any node framework
- To test the mobile native app, I suggest you start it manually as I am not sure how we could nicely deal with device simulators 

For non node framework like flutter, in theory it should be possible but I am not sure if it would fit the Quinoa workflow.

Let's keep this issue open as a reminder for me to have look ;-)

**Comment by edufolly** [comment]
I would like to create a Flutter Web SPA and deploy with Quarkus backend. Inside the same container image.

**Comment by ia3andy** [comment]
We could imagine having something like this:
```properties
quarkus.quinoa.custom-package-manager.install=some-binary install
quarkus.quinoa.custom-package-manager.dev=some-binary start
quarkus.quinoa.custom-package-manager.build=some-binary build
quarkus.quinoa.custom-package-manager.test=some-binary test

**Comment by ia3andy** [comment]
See #133
