### ISSUE TITLE
Unexpected deletion of served Folder

### ISSUE THREAD

**Issue by Joofthan** [quarkiverse/quarkus-quinoa#94]
In Svelte "src/main/webui/public/" should be served. But only the build folder is regenerated "src/main/webui/public/build/"

In documentation it says it copies the content of "quarkus.quinoa.build-dir" but it is moving or deleting the folder

3 Possible solutions:
- Mention deletion of served folder in documentation
- different paths for deletion and serving
- disable deletion of build folder

**Comment by ia3andy** [comment]
You are right, it should mention that the build directory is moved (and not copied) would you provide a PR?

**Comment by ia3andy** [comment]
@Joofthan I've tried svelte-kit and it seems to have an output directory:
```
.svelte-kit/output/server/manifest.json                         2.33 KiB
.svelte-kit/output/server/index.js                              74.23 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.ts.js   1.33 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js      10.63 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js     0.72 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js         1.51 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js         9.71 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js   9.70 KiB
.svelte-kit/output/server/chunks/index-5d6c164c.js              3.95 KiB
.svelte-kit/output/server/chunks/hooks-93fa095d.js              0.46 KiB
```

I you are using Rollup, I suggest you just change the config to generate all in a single output directory (copy the public content) like most frameworks do.

**Comment by ia3andy** [comment]
Ok it seems svelte-kit is for a different purpose, I've tried with what they suggest on the svelte template repo (https://github.com/sveltejs/template):
```
npm init vite
```

It works fine: https://github.com/ia3andy/quinoa-svelte

I also added a fetch on the backend.

**Comment by Joofthan** [comment]
Thank You for looking into it. I used the command on the Svelte-Homepage many months ago to create the template. It is Rollup. I did not know they switched to vite.

EmptyProject with Rollup: https://gitlab.com/joofthan/templates/quarkus-svelte-fullstack/-/tree/master/src/main/javascript
MyRealProject: https://gitlab.com/joofthan/multithek/-/tree/master/multithek-main

**Comment by ia3andy** [comment]
@Joofthan I will have a look to your specific case tomorrow

**Comment by ia3andy** [comment]
@Joofthan here is how to make it work:
https://github.com/ia3andy/quarkus-svelte-fullstack/commit/2391951e7ebbe3e30c284e006bf4e4d94a05531d

**Comment by Joofthan** [comment]
Many Thanks!
