### ISSUE TITLE
Next.js Compatibility - Not forwarding to root

### ISSUE THREAD

**Issue by adamhenderson** [quarkiverse/quarkus-quinoa#97]
Similar to https://github.com/quarkiverse/quarkus-quinoa/issues/67 when using Next.js as the UI hitting the root (http://localhost:8080) does not forward to the Next.js home page instead returning "Resource not found" 404.

Hitting the root of the dev server works as expected: http://localhost:3000

quarkus: 2.9.2
quarkus-quinoa:1.0.5

**Comment by ia3andy** [comment]
@adamhenderson isn't next.js supposed to be a server?

**Comment by adamhenderson** [comment]
TBH, I'm going through experimenting with frameworks and just trying things out - yes there is a server side component to it, so this is probably an invalid requirement. Even so, I was reporting that the forwarding from 8080 to the dev server on 3000 did not seem to be working as expected.

Happy for you to close this there is no issue.

(great work btw :) )

**Comment by ia3andy** [comment]
As soon as the forwarding works in valid cases, it's OK.

This is a DEV feature, if there is a bug behind this issue, we can wait for it to pop up with another valid framework :)

Thanks for reporting anyway!

**Comment by melloware** [comment]
I opened this new ticket in regards to NextJS: https://github.com/quarkiverse/quarkus-quinoa/issues/268
